# Generated by Django 2.2.5 on 2021-04-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('age', models.CharField(max_length=400)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonenumber', models.CharField(max_length=400)),
                ('Type_of_car', models.CharField(max_length=400)),
                ('carnumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Truckse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=50, null=True)),
                ('client_name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=400)),
                ('Type_of_load', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=400)),
                ('To', models.CharField(max_length=400)),
                ('The_beneficial_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Taxi_app.Drivers')),
            ],
        ),
        migrations.CreateModel(
            name='Taxie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=50, null=True)),
                ('client_name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=400)),
                ('age_of_driver', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=400)),
                ('To', models.CharField(max_length=400)),
                ('The_beneficial_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Taxi_app.Drivers')),
            ],
        ),
        migrations.CreateModel(
            name='Buse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=50, null=True)),
                ('client_name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=400)),
                ('To', models.CharField(max_length=400)),
                ('The_beneficial_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Taxi_app.Drivers')),
            ],
        ),
    ]
